#!/bin/sh /etc/rc.common
# /etc/init.d/dnsapi

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /root/dnsmasq-driver/dnsmassq-api-driver.py
    procd_set_param respawn
    procd_close_instance
}